"""Regenerate render.yaml from the persona roster.

Use this when you want to scale up (5 → 20 services) or change a service
parameter across all bots at once. Reads bot/persona.py for the roster.

Usage:
    python scripts/gen_render_yaml.py              # all 20 personas
    python scripts/gen_render_yaml.py --first 5    # boss + 4 leads (default farm-foundation)
    python scripts/gen_render_yaml.py --keys boss,research_lead

Output goes to ``render.yaml`` (overwrites). Diff before committing.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Make ``bot`` importable when run from repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from bot.persona import list_personas  # noqa: E402

HEADER = """# Render Blueprint — https://render.com/docs/infrastructure-as-code
#
# Generated by scripts/gen_render_yaml.py — DO NOT hand-edit individual
# service blocks. Edit bot/persona.py to add/rename personas, then
# regenerate:
#
#     python scripts/gen_render_yaml.py --first 5    # boss + 4 leads
#     python scripts/gen_render_yaml.py              # full 20-bot farm
#
# Usage on Render:
#   1. https://dashboard.render.com → New + → Blueprint
#   2. Connect this GitHub repo
#   3. Render reads this file and asks for each service's BOT_TOKEN
#      — leave it EMPTY for any bot you haven't created in BotFather
#      yet. Those services boot in dormant mode (only /healthz).
#   4. Apply → each service auto-deploys with its own 1GB persistent disk
#   5. /start each bot in Telegram → claim ownership → /setup → API key
#   6. To activate a dormant bot later: Render dashboard → service →
#      Environment → set BOT_TOKEN → save (service auto-restarts)

services:
"""

SERVICE_TEMPLATE = """
  # ===== {index}. {display_name} =================================================
  - type: web
    name: lilush-{service_suffix}
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_PERSONA
        value: {persona_key}
      - key: BOT_TOKEN
        sync: false        # set in Render dashboard
      - key: BOT_MODE
        value: polling
      - key: PORT
        value: 8080
      - key: DATA_DIR
        value: /data
      - key: ALLOWED_USER_IDS
        sync: false
    disk:
      name: lilush-{service_suffix}-data
      mountPath: /data
      sizeGB: 1
"""


def render_yaml(persona_keys: list[str]) -> str:
    """Render the yaml body for the given subset of personas."""
    personas = {p.key: p for p in list_personas()}
    out = [HEADER]
    for idx, key in enumerate(persona_keys, start=1):
        persona = personas.get(key)
        if persona is None:
            raise SystemExit(f"unknown persona key: {key!r}")
        service_suffix = key.replace("_", "-")
        out.append(
            SERVICE_TEMPLATE.format(
                index=idx,
                display_name=persona.display_name,
                service_suffix=service_suffix,
                persona_key=persona.key,
            )
        )
    return "".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--first",
        type=int,
        default=None,
        help="emit only the first N personas in roster order",
    )
    parser.add_argument(
        "--keys",
        type=str,
        default=None,
        help="comma-separated explicit list of persona keys (overrides --first)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "render.yaml",
        help="output path (default: ./render.yaml)",
    )
    args = parser.parse_args()

    all_keys = [p.key for p in list_personas()]
    if args.keys:
        keys = [k.strip() for k in args.keys.split(",") if k.strip()]
    elif args.first is not None:
        keys = all_keys[: args.first]
    else:
        keys = all_keys

    yaml = render_yaml(keys)
    args.out.write_text(yaml)
    print(f"wrote {args.out} with {len(keys)} service block(s):")
    for k in keys:
        print(f"  - {k}")


if __name__ == "__main__":
    main()
